version: "3.7"
services:
  db:
    container_name: ts_mysql
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      - net
networks:
  net:
 
